### ISSUE TITLE
[Feature Request]: Create a Profile Page Layout Component

### ISSUE THREAD

**Issue by RISHIKESHk07** [bsoc-bitbyte/busify#81]
### Is your feature request related to a problem? Please describe.

Create a profile page design according to the provided Figma file . The solution should have three components:
1. Profile details component: This component should display the user's avatar and credentials .
2. Upcoming journey layout component: Display Upcoming journey layout as per figma design .
3. Completed journey layout component: Display Completed journey layout as per figma design .
4. In the two above points 2 & 3 you need to create just a layout for both of them , not the cards as well , you can leave the cards 
    empty for now .

## Figma File
[Figma File Link](https://www.figma.com/design/dhFhm64op9fcre1hbsGTab/Busify?node-id=4-483&t=OJIol54MEYnMX7Lz-0)

## Tasks
- [ ] Create the profile details component according to the Figma design .
- [ ] Design the  Completed journey layout component  & Upcoming journey layout component
- [ ] Ensure responsiveness on all screens

## Additional Details
- Use appropriate colors, fonts, and spacing as per the design.
- Consider responsiveness for different screen sizes.
- Ensure consistency with the overall design theme.

**Comment by rohansen856** [comment]
I would like to work on this issue. Can you please provide access to the figma file as it seems to be protected.

**Comment by Vaibhavsahu2810** [comment]
@RISHIKESHk07 I would like work on this issue.I will create profile page and make it responsive according to the provided figma file

**Comment by RISHIKESHk07** [comment]
@rohansen856  DM your email on discord

**Comment by rohansen856** [comment]
@RISHIKESHk07 i have created the responsive profile page layout. i am attaching the screenshots on different device dimensions. please reply if this is ok, or any other changes are needed...

![Screenshot 2024-06-04 141132](https://github.com/bsoc-bitbyte/busify/assets/108976786/826ded30-40f6-4f9c-af40-819e80e81717)
![Screenshot 2024-06-04 141107](https://github.com/bsoc-bitbyte/busify/assets/108976786/5d811d3f-a54d-4850-a5ec-55d9f8076f0c)
![Screenshot 2024-06-04 141148](https://github.com/bsoc-bitbyte/busify/assets/108976786/b4d072a9-4b47-49c7-ba1a-e818a6717b52)

**Comment by rohansen856** [comment]
layout with demo cards:
![Screenshot 2024-06-04 144733](https://github.com/bsoc-bitbyte/busify/assets/108976786/9cfa5a0e-c897-4500-899b-890e74c07537)
![Screenshot 2024-06-04 144817](https://github.com/bsoc-bitbyte/busify/assets/108976786/14620009-b801-4893-a3ac-1d81e28f3521)
![Screenshot 2024-06-04 144805](https://github.com/bsoc-bitbyte/busify/assets/108976786/8b028063-bf57-4e05-8ef8-8f73652cad16)
![Screenshot 2024-06-04 144746](https://github.com/bsoc-bitbyte/busify/assets/108976786/d517956c-43c1-4206-a572-8ec720519202)

**Comment by RISHIKESHk07** [comment]
@rohansen856 the user details can be obtained from AuthStore context .

**Comment by rohansen856** [comment]
@RISHIKESHk07  ok.. i will implement that and also make it a protected route.

**Comment by RISHIKESHk07** [comment]
@rohansen856 you can refer the PROFILE Completed version in the figma file , and as for the protected route , it can be done later after we integrate the fetching logic (which will be another issue) .

**Comment by rohansen856** [comment]
@RISHIKESHk07 i have updated the profile page accrording to the figma file along with adding user auth in pr #83. thank you.
