### ISSUE TITLE
[Feature Request]: Create Ticket Card Components

### ISSUE THREAD

**Issue by RISHIKESHk07** [bsoc-bitbyte/busify#82]
## Description
Create a reusable UI components for the ticket card to be used in both Upcoming and Completed sections. Refer the figma design under the profile page , you have two layouts Completed & Upcoming , under these we have Card components which you have to create.

## Figma File
[Figma File Link](https://www.figma.com/design/dhFhm64op9fcre1hbsGTab/Busify?node-id=4-483&t=OJIol54MEYnMX7Lz-0)

## Tasks
- [ ] Design the ticket card components according to the provided Figma design.
- [ ] Create a ticket card component for the Upcoming Section
- [ ] Create a ticket card component for the Completed Section
- [ ] Use dummy data as represented in the figma file.
- [ ] Make the ticket card components reusable and easily customizable.

## Additional Details
- Use appropriate colors, fonts, and spacing as per the design.
- Consider responsiveness for different screen sizes.
- Ensure consistency with the overall design theme.

**Comment by ritankarsaha** [comment]
I would like to work on this issue. Approach would be direct to create the reusable UI card components for the ticket card, adhering to the figma design.
Please assign me this issue.
Thank you.

**Comment by ritankarsaha** [comment]
@RISHIKESHk07 Could you pls grant access to the figma design file? It appears to be protected.

**Comment by RISHIKESHk07** [comment]
@ritankarsaha DM your email on discord

**Comment by ritankarsaha** [comment]
> @ritankarsaha DM your email on discord

@RISHIKESHk07 I have.
Thank you.

**Comment by ritankarsaha** [comment]
@RISHIKESHk07 I have fixed the issue #82 and opened a PR for the same #84.
Thank You.

**Comment by ritankarsaha** [comment]
@RISHIKESHk07 made the necessary changes and pushed the commit.
