### ISSUE TITLE
[Feature Request]:  Implement Dynamic Cards for Ticket Page

### ISSUE THREAD

**Issue by RISHIKESHk07** [bsoc-bitbyte/busify#88]
### Is your feature request related to a problem? Please describe.

The current implementation of ticket page cards involves hard-coded data. To make the cards dynamic, the data needs to be fetched from the backend. This task requires fetching data using Nest.js, Prisma, and PostgreSQL, and placing the information accurately where it's required. Dummy data can be inserted into the database for testing purposes.

Refer issue #82 for Created Card components , you will have just fetch data and insert it into the componenets

### Describe the solution you'd like

# Tasks
- [ ] If their is no suitable route in backend (nest) for fetching data , ping us once to know before starting
- [ ] Update the ticket page to dynamically populate cards with fetched data.
- [ ] Ensure accurate placement of information on the cards as per requirements.
- [ ] Insert accurate dummy data into the database for testing purposes.

### Developer Help

Ping us once before starting this issue on discord

**Comment by Vaibhavsahu2810** [comment]
@RISHIKESHk07 i would like to work on this issue. To fetch data from backend i will create a file in backend/src and create a new function in its service.ts to fetch data from prisma command .findMany() and create a controller.ts to use this function . after that to seed the data i will create a file seed.ts in prisma folder and seed data using .createMany() function then i will populate this data in frontend file.

**Comment by Om-Thorat** [comment]
hello, I would like to work on this issue i will create 3 files ie `ticket.controller.ts , ticket.module.ts , ticket.service.ts` in the backend/src folder. I'll use the ticket model described in schema.prisma or modify it if needed and put the demo data in `seed.mjs` . On the frontend i'll use axios on the frontend to fetch the data and will send it withcredentials too, from the backend i'll ensure only the tickets for the logged in user are fetched and sent to the frontend.

**Comment by RISHIKESHk07** [comment]
@Vaibhavsahu2810 will be taking this one ,as he commented this first

**Comment by RISHIKESHk07** [comment]
@Om-Thorat this is open  #90

**Comment by Vaibhavsahu2810** [comment]
@RISHIKESHk07 please provide me access of figma file email id - sahusv4527@gmail.com
