### ISSUE TITLE
[Feature Request]: Implement Admin Dashboard UI According to Figma Design

### ISSUE THREAD

**Issue by RISHIKESHk07** [bsoc-bitbyte/busify#89]
### Is your feature request related to a problem? Please describe.

Replicate the design provided in the Figma file to create an admin dashboard. This involves two main tasks:

1. Retrieve Data from Backend:  fetch necessary data from the backend.
2. UI Implementation:
   - Create two components based on the Figma design:
     - Single Card Component: Display all tickets sold in a single card format.
     - List Component: Render all tickets as a list below the card, adhering to the Figma design.
     - Modal Component: Develop a modal using MUI to display the full details of a ticket.

## Figma File
[Figma File Link](https://www.figma.com/design/dhFhm64op9fcre1hbsGTab/Busify?node-id=4-483&t=OJIol54MEYnMX7Lz-0)

# Tasks
- [ ] Implement Single Card Component for displaying tickets of the day.
- [ ] Implement List Component to render all tickets according to the Figma design.
- [ ] Create a Modal Component to show full details of a ticket.
- [ ] Create a route in the backend if required if no route does not match requirements & do ping us once before starting this 
- [ ] Insert accurate dummy data into the database for testing purposes.

### Developer Help

ping us on discord before starting this issue

**Comment by rohansen856** [comment]
@RISHIKESHk07 i would like to work on this issue. i will create the necessary components according to the figma design using material ui.
> i will create a backend route to fetch the ticket by the `Order` schema in prisma with correct `status` to fetch all the sold tickets. 
> also i will filter the tickets using `createdAt` filter to the current day.
> i will use the `Ticket` and `Schedule` schema to create the data for the ticket details.

**Comment by rohansen856** [comment]
@RISHIKESHk07 @Pratik2026 i have solved this issue and made a pr #92. thank you.
